<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Nullable>enable</Nullable>
    <Deterministic>true</Deterministic>
    <Authors>Navz</Authors>
    <Company>Navz</Company>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/rmnavz/Navz.PluginEngine.Core</RepositoryUrl>
    <PackageProjectUrl>https://github.com/rmnavz/Navz.PluginEngine.Core</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>
</Project>
