<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <Nullable>enable</Nullable>
  </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)'=='Debug'">
      <DefineConstants>DEBUG;TEST_CONFIG_DEBUG</DefineConstants>
    </PropertyGroup>
    <PropertyGroup Condition="'$(Configuration)'=='Release'">
      <DefineConstants>RELEASE;TEST_CONFIG_RELEASE</DefineConstants>
    </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Moq" Version="4.20.72" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="5.0.0" />
    <PackageReference Include="coverlet.collector" Version="6.0.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Navz.PluginEngine.Abstractions\Navz.PluginEngine.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\Navz.PluginEngine.Host\Navz.PluginEngine.Host.csproj" />
  </ItemGroup>
</Project>
